### ISSUE TITLE
Error 403 on pulling image

### ISSUE THREAD

**Issue by irwan-runtuwene** [WhatsApp/WhatsApp-Business-API-Setup-Scripts#57] opened 2021-03-09 14:01 UTC
it's similar with #23 when running docker-compose from indonesia
docker-compose up -d
Pulling wacore (docker.whatsapp.biz/coreapp:v2.33.3)...
v2.33.3: Pulling from coreapp
83ee3a23efb7: Pulling fs layer
db98fc6f11f0: Pulling fs layer
f611acd52c6c: Pulling fs layer
f85e9fda1e76: Waiting
8031e26de4a5: Waiting
d75c233db377: Waiting
eb6a89aa8799: Waiting
dea8a3ecac8b: Waiting
ea976d199fd6: Waiting
ERROR: error pulling image configuration: error parsing HTTP 403 response body: invalid character 'F' looking for beginning of value: "Forbidden!"

I'm using ubuntu 16.04 i've tried using 2 different block IP from my provider but seems both was blocked.

**Comment by uguracikgoz** [comment] 2021-03-14 21:59
Hello i have been facing the same problem :
Failed to pull image "docker.whatsapp.biz/web:v2.33.3": rpc error: code = Unknown desc = error pulling image configuration: error parsing HTTP 403 response body: invalid character 'F' looking for beginning of value: "Forbidden!"

**Comment by pablotdv** [comment] 2021-05-12 18:05
The same problem here.

There's any solution?

**Comment by paulolima-gb** [comment] 2021-05-12 20:13
Hello, same problem here. Is there any workaround?

**Comment by huseyin** [comment] 2021-05-25 12:47
Having the same issue. I exported a full copy of an existing image on my another machine as a workaround. It did work well but of course it is not sustainable.

**Comment by johns00n** [comment] 2021-05-25 13:59
Having the same issue. I exported a full copy of an existing image on my another machine as a workaround. It did work well but of course it is not sustainable. I suspected I had a banned IP but I noticed the image URL was unreachable when tried over web browser. It redirected me an unknown page. That is a side note about my issue.

It is likely that the problem is based on IPs. I successfully pulled the required images on a DigitalOcean machine. I think some countries are restricted to perform this action.

**Comment by AMhaish** [comment] 2021-06-07 19:24
I am getting same error with different message as next:

Failed to pull image "docker.whatsapp.biz/web:v2.35.2": rpc error: code = Unknown desc = failed to pull and unpack image "docker.whatsapp.biz/web:v2.35.2": failed to copy: httpReaderSeeker: failed open: unexpected status code https://docker.whatsapp.biz/v2/web/blobs/sha256:fb6b73cdf53fd33f267f453876cd8e9daf2ce96a89630833a7c29ba7a1b2a797: 403 Forbidden

Any idea why I am getting that?

**Comment by ben221199** [comment] 2021-06-07 20:11
Yes:
![image](https://user-images.githubusercontent.com/12856904/121081633-425ca600-c7dd-11eb-9a3b-024b585cf9c1.png)

**Comment by chillprakash** [comment] 2021-06-08 12:38
Same issue.

**Comment by nathanaelreges** [comment] 2021-06-10 09:26
Guys I solved this problem by upgrading my docker version!
From: Docker version 19.03.13, build 4484c46d9d
To: Docker version 20.10.7, build f0df350
Does it works for you to?

**Comment by rogerweb** [comment] 2021-06-23 14:57
It doesn't. I'm on 20.10.7 too and getting the same error.

**Comment by saurav955** [comment] 2021-06-24 04:16
I installed the whole thing about 15days ago and everything worked (both coreapp and webapp images got pulled). Now I am trying to setup Instance Monitoring and getting the Forbidden error.

<Pulling prometheus (docker.whatsapp.biz/prometheus:v2.33.4)...
v2.33.4: Pulling from prometheus
76df9210b28c: Downloading
559be8e06c14: Downloading
0f8c479799f2: Downloading
18b600182fb7: Downloading
7107ca4b8b6a: Download complete
6d4f7a6bf1de: Download complete
70791e712bf8: Download complete
11ccf794006c: Download complete
44dc96c0af43: Download complete
ecdf06ab4b8d: Download complete
50e51d4c12aa: Download complete
c37593abaed6: Download complete
66651f4989d8: Downloading
09a620c94a47: Download complete
ERROR: Forbidden
>

Tried to pull the webapp image and now it gives the same error as well. My docker version is 20.10.7

**Comment by saurav955** [comment] 2021-06-24 04:17
I installed the whole thing about 15days ago and everything worked (both coreapp and webapp images got pulled). Now I am trying to setup Instance Monitoring and getting the Forbidden error.

```
Pulling prometheus (docker.whatsapp.biz/prometheus:v2.33.4)...
v2.33.4: Pulling from prometheus
76df9210b28c: Downloading
559be8e06c14: Downloading
0f8c479799f2: Downloading
18b600182fb7: Downloading
7107ca4b8b6a: Download complete
6d4f7a6bf1de: Download complete
70791e712bf8: Download complete
11ccf794006c: Download complete
44dc96c0af43: Download complete
ecdf06ab4b8d: Download complete
50e51d4c12aa: Download complete
c37593abaed6: Download complete
66651f4989d8: Downloading
09a620c94a47: Download complete
ERROR: Forbidden
```

Tried to pull the webapp image and now it gives the same error as well. My docker version is 20.10.7

**Comment by ben221199** [comment] 2021-06-24 08:35
It does not work because BinTray only allows paid users until July 4th. All other users get a `Forbidden`. WhatsApp should move the Docker image to another location in order to work.

**Comment by emreoztoprak** [comment] 2021-07-05 10:37
i dont get 403 error but i cant pull image too

Pulling wacore (docker.whatsapp.biz/coreapp:v2.35.4)...
ERROR: error unmarshalling content: invalid character '<' looking for beginning of value

**Comment by tejassolanki312** [comment] 2021-07-05 11:48
> 
> 
> i dont get 403 error but i cant pull image too
> 
> Pulling wacore (docker.whatsapp.biz/coreapp:v2.35.4)...
> ERROR: error unmarshalling content: invalid character '<' looking for beginning of value

yes its because the access to bintray has now been forbidden.

**Comment by ben221199** [comment] 2021-07-05 16:31
Yesterday was the last day that BinTray could be used. WhatsApp should now move the image to another system so that we could download it again.

**Comment by felippebueno** [comment] 2021-07-05 17:05
Is there an alternative repository, or do we have to wait? My first setup and I don't really understand if I should wait or look for an alternative.

If necessary to wait, how long do you have an idea?

**Comment by ben221199** [comment] 2021-07-05 19:30
I asked someone if he could forward this issue to a Facebook/WhatsApp guy he knows. Hopefully I get a response soon.

**Comment by caiokawasaki** [comment] 2021-07-05 19:42
![image](https://user-images.githubusercontent.com/9747004/124512883-deafa380-ddaf-11eb-850e-e84bbe9e0ba3.png)
Did anyone get this issue while trying to download the new version?

**Comment by ben221199** [comment] 2021-07-05 19:54
Does nobody read or something? 🤨

**Comment by nvlan** [comment] 2021-07-05 20:35
This issue is happening with every version: the registry docker.whatsapp.biz is no longer accesible.

**Comment by felippebueno** [comment] 2021-07-06 00:00
It seems to be waiting until a new repository is available for download. My first setup hahaha very unlucky.

**Comment by arasusara** [comment] 2021-07-06 03:08
If the setup was done in AWS, Please refer to https://developers.facebook.com/docs/whatsapp/installation. I am getting unauthorized error. Check your "/var/log/messages"

Jul  6 02:54:54 ip-172-31-28-44 dockerd: time="2021-07-06T02:54:54.683926345Z" level=info msg="Attempting next endpoint for pull after error: unauthorized"
Jul  6 02:54:54 ip-172-31-28-44 dockerd: time="2021-07-06T02:54:54.686038201Z" level=error msg="Handler for POST /v1.41/images/create returned error: unauthorized"

**Comment by caiokawasaki** [comment] 2021-07-06 18:22
Has anyone opened a ticket on Facebook support? If not, I'll open it in one of our Wabas...

**Comment by chillprakash** [comment] 2021-07-07 00:11
Had the same Issue. Checked with WhatsApp and was told that this is an intermittent issue. Resolved after a while without doing anything.

**Comment by mengyiyuan** [comment] 2021-07-08 07:51
Hello everyone,
I am very sorry about the late reply. We had an issue with the Docker repo earlier this week, which is why you were not able to pull the images during that time. We are improving our outage communications with our status page: https://status.fb.com/whatsapp-business-api, where you could refer to for future outages.

Sorry again for the inconvenience caused, feedback to improve our support process is welcome. :)

**Comment by mengyiyuan** [comment] 2021-07-21 11:39
Duplicate of #38 - merging this thread with a previous one, closing this one.

**Closed by mengyiyuan** 2021-07-21 11:39 UTC
